version: 2

jobs:
  # The deploy job
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:14.9.0-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout    
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Install AWS cli
      - run:
          name: Install aws cli
          command: sudo apt-get -y -qq  --fix-missing install awscli
      # Set the signature version for the S3 auth
      - run:
          name: Setting Signature Version 4 for S3 Request Authentication
          command: aws configure set default.s3.signature_version s3v4
      # Deploy to the S3 bucket corresponding to the current branch
      - run:
          name: Deploy to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
                aws --region eu-west-1 s3 sync . s3://experts-circle-dev-publicweb-origin/ --delete
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                aws --region eu-west-1 s3 sync . s3://experts-circle-staging-publicweb-origin/ --delete
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                aws --region eu-west-1 s3 sync . s3://experts-circle-dev-publicweb-origin/ --delete
            fi

workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      # The deploy job will only run on the filtered branches and
      # require the build job to be successful before it starts
      - deploy:
          filters:
            branches:
              only:
                - develop
                - staging
                - master